# Generated by Django 2.1.3 on 2018-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musico',
            name='idade',
        ),
        migrations.AddField(
            model_name='banda',
            name='criacao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='musico',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='musico',
            name='nascimento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
