# Generated by Django 2.1.3 on 2018-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181110_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='musico',
            name='genero',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
