# Generated by Django 2.1.3 on 2018-11-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musico_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='genero',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
